### ISSUE TITLE
@tailwind preflight not valid

### ISSUE THREAD

**Issue by carlituxman** [Naoray/dark-tailwind-preset#4]
`@tailwind preflight` is not a valid at-rule in Tailwind v1.0, use `@tailwind base` instead.

**Comment by Naoray** [comment]
This preset currently uses tailwind v0.7.4, therefore `@tailwind preflight` is still valid. If you want to update this package to v1.0 you are welcome to submit a PR

**Comment by Naoray** [comment]
@carlituxman I just released a new version which uses tailwind 1.0 by default
